@extends('backend.layouts.app')
@section('content')
<div class="container-fluid"><h3 class="mb-4">Homepage Content</h3>@if(session('message'))<div class="alert alert-success">{{session('message')}}</div>@endif
@foreach($sections as $type=>$section)<div class="card mb-4"><div class="card-header"><h4>{{$section['label']}}</h4></div><div class="card-body">
    @foreach($section['records'] as $record)<form method="POST" enctype="multipart/form-data" action="{{route('admin.homepage-content.save',[$type,$record->id])}}" class="row g-3 border rounded p-3 mb-3">@csrf
        @foreach($section['fields'] as $field=>$kind)<div class="{{in_array($kind,['textarea'])?'col-12':'col-md-4'}}"><label class="form-label">{{str($field)->replace('_',' ')->title()}}</label>@if($kind==='textarea')<textarea name="{{$field}}" class="form-control" rows="3">{{old($field,$record->$field)}}</textarea>@elseif($kind==='image')<input type="file" name="{{$field}}" class="form-control" accept="image/*">@if($record->$field)<small><a href="{{Storage::url($record->$field)}}" target="_blank">Current image</a></small>@endif @elseif($kind==='checkbox')<div class="form-check"><input type="checkbox" name="{{$field}}" value="1" class="form-check-input" @checked(old($field,$record->$field))></div>@else<input type="{{$kind}}" name="{{$field}}" value="{{old($field,$kind==='datetime-local'?$record->$field?->format('Y-m-d\TH:i'):$record->$field)}}" class="form-control" @if($kind==='number') step="0.01" @endif>@endif</div>@endforeach
        <div class="col-12 form-check ms-2"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="active-{{$type}}-{{$record->id}}" @checked($record->is_active)><label class="form-check-label" for="active-{{$type}}-{{$record->id}}">Active</label></div><div class="col-12"><button class="btn btn-primary">Update</button> <button class="btn btn-danger" type="submit" form="delete-{{$type}}-{{$record->id}}">Delete</button></div>
    </form><form id="delete-{{$type}}-{{$record->id}}" method="POST" action="{{route('admin.homepage-content.delete',[$type,$record->id])}}">@csrf @method('DELETE')</form>@endforeach
    <h5 class="mt-4">Add New</h5><form method="POST" enctype="multipart/form-data" action="{{route('admin.homepage-content.save',$type)}}" class="row g-3 bg-light rounded p-3">@csrf
        @foreach($section['fields'] as $field=>$kind)<div class="{{in_array($kind,['textarea'])?'col-12':'col-md-4'}}"><label class="form-label">{{str($field)->replace('_',' ')->title()}}</label>@if($kind==='textarea')<textarea name="{{$field}}" class="form-control" rows="3"></textarea>@elseif($kind==='checkbox')<div class="form-check"><input type="checkbox" name="{{$field}}" value="1" class="form-check-input"></div>@else<input type="{{$kind}}" name="{{$field}}" class="form-control" @if($kind==='image') accept="image/*" @endif @if($kind==='number') step="0.01" @endif>@endif</div>@endforeach<div class="col-12 form-check ms-2"><input class="form-check-input" type="checkbox" name="is_active" value="1" checked id="new-active-{{$type}}"><label class="form-check-label" for="new-active-{{$type}}">Active</label></div><div class="col-12"><button class="btn btn-success">Add {{$section['label']}} Item</button></div>
    </form>
</div></div>@endforeach</div>
@endsection
