@extends('frontend.layouts.app')
@section('title',$page->meta_title ?: $page->title)
@section('meta_description',$page->meta_description)
@section('content')
@include('frontend.pages.partials.breadcrumb',['page'=>$page])
@php($sections=$page->sections?:[])
<section class="choose-us-section section-padding"><div class="container"><div class="row g-5 align-items-center"><div class="col-lg-6"><div class="section-title"><span>Why Choose Us</span><h2>{{data_get($sections,'promise_title','Quality, service, and memorable travel')}}</h2></div><p class="mt-3">{{$page->content}}</p></div><div class="col-lg-6"><div class="row g-3">@foreach(data_get($sections,'promises',[]) as $promise)<div class="col-md-6"><div class="p-4 bg-white shadow-sm rounded h-100"><i class="far fa-check-circle text-primary fs-3"></i><h5 class="mt-3">{{$promise}}</h5></div></div>@endforeach</div></div></div></div></section>
@if(data_get($sections,'counters'))<section class="counter-section section-padding section-bg"><div class="container"><div class="row g-4 text-center">@foreach(data_get($sections,'counters',[]) as $counter)<div class="col-6 col-lg-3"><h2 class="text-primary">{{data_get($counter,'value')}}</h2><p>{{data_get($counter,'label')}}</p></div>@endforeach</div></div></section>@endif
@if(data_get($sections,'show_destinations') && $destinations->isNotEmpty())<section class="destination-section section-padding"><div class="container"><div class="section-title-area"><div class="section-title"><span>Explore</span><h2>Popular Destinations</h2></div><a href="{{route('destination.index')}}" class="theme-btn"><span>View all</span></a></div><div class="swiper destination-slider"><div class="swiper-wrapper">@foreach($destinations as $destination)<div class="swiper-slide"><a href="{{route('destination.show',$destination)}}" class="d-block"><div class="destination-card-items"><div class="destination-image"><img class="w-100" src="{{Storage::url($destination->image)}}" alt="{{$destination->name}}"></div><h4 class="mt-3">{{$destination->name}}</h4></div></a></div>@endforeach</div><div class="swiper-pagination"></div></div></div></section>@endif
@if(data_get($sections,'show_team') && $members->isNotEmpty())<section class="team-section section-padding section-bg"><div class="container"><div class="section-title text-center"><span>Our People</span><h2>Meet the Team</h2></div><div class="row g-4 mt-2">@foreach($members as $member)<div class="col-lg-3 col-md-6"><div class="team-card-items text-center"><a href="{{route('team.show',$member)}}"><img class="img-fluid rounded" src="{{Storage::url($member->image)}}" alt="{{$member->name}}"><h4 class="mt-3">{{$member->name}}</h4></a><p>{{$member->role}}</p></div></div>@endforeach</div></div></section>@endif
@if(data_get($sections,'show_app'))<section class="cta-section section-padding"><div class="container"><div class="p-5 rounded text-center section-bg"><h2>{{data_get($sections,'app_title','Plan your next journey with Aventaro')}}</h2><p class="mt-3">{{data_get($sections,'app_text')}}</p><a class="theme-btn mt-3" href="{{route('tour.index')}}"><span>Explore tours</span></a></div></div></section>@endif
@if(data_get($sections,'show_news') && $posts->isNotEmpty())<section class="news-section section-padding"><div class="container"><div class="section-title-area"><div class="section-title"><span>Travel Journal</span><h2>Latest News</h2></div><a href="{{route('news.index')}}" class="theme-btn"><span>All news</span></a></div><div class="row g-4">@foreach($posts as $post)<div class="col-lg-4"><article class="single-blog-post"><a href="{{route('news.show',$post)}}"><img class="img-fluid w-100" src="{{Storage::url($post->image)}}" alt="{{$post->title}}"><h4 class="mt-3">{{$post->title}}</h4></a><p>{{$post->excerpt}}</p></article></div>@endforeach</div></div></section>@endif
<script>document.addEventListener('DOMContentLoaded',function(){if(window.Swiper&&document.querySelector('.destination-slider'))new Swiper('.destination-slider',{slidesPerView:1,spaceBetween:24,pagination:{el:'.destination-slider .swiper-pagination',clickable:true},breakpoints:{768:{slidesPerView:2},1200:{slidesPerView:4}}});});</script>
@endsection
