<div>
@if($benefits->isNotEmpty())<div class="marquee-section fix section-padding pt-0"><div class="marque-wrapper style-2"><div class="swiper text-slider"><div class="swiper-wrapper slide-transtion">@foreach($benefits as $benefit)<div class="swiper-slide brand-slide-element" wire:key="benefit-{{$benefit->id}}"><div class="marque-text"><img src="{{$benefit->icon?Storage::url($benefit->icon):asset('assets/frontend/img/marque.png')}}" alt=""><h3>{{$benefit->title}}</h3></div></div>@endforeach</div></div></div></div>@endif

@if($team->isNotEmpty())<section class="team-section-4 section-padding pt-0"><div class="container"><div class="section-title text-center"><span>Our Team</span><h2>Tours Guiding Team</h2></div><div class="row">@foreach($team as $member)<div class="col-xl-3 col-lg-4 col-md-6" wire:key="team-{{$member->id}}"><div class="team-card-items-4"><div class="thumb"><a href="{{route('team.show',$member)}}"><img src="{{Storage::url($member->image)}}" alt="{{$member->name}}"></a></div><div class="content"><span>{{$member->role}}</span><h3><a href="{{route('team.show',$member)}}">{{$member->name}}</a></h3><div class="social-icon">@if($member->facebook_url)<a href="{{$member->facebook_url}}" target="_blank" rel="noopener"><i class="fab fa-facebook-f"></i></a>@endif @if($member->twitter_url)<a href="{{$member->twitter_url}}" target="_blank" rel="noopener"><i class="fab fa-twitter"></i></a>@endif @if($member->instagram_url)<a href="{{$member->instagram_url}}" target="_blank" rel="noopener"><i class="fab fa-instagram"></i></a>@endif</div></div></div></div>@endforeach</div><div class="text-center mt-5"><a href="{{route('team.index')}}" class="theme-btn"><span>View All Members</span></a></div></div></section>@endif

@if($categories->isNotEmpty()||$promo)<section class="top-destination-section-4 section-padding pb-0"><div class="container">@if($categories->isNotEmpty())<div class="section-title-area"><div class="section-title"><span>Travel Inspiration</span><h2>Inspiration for Future Travel</h2></div><a href="{{route('tour.index')}}" class="theme-btn theme-btn-2"><span>Explore More</span></a></div><div class="row">@foreach($categories as $category)<div class="col-xl-3 col-lg-4 col-md-6" wire:key="category-{{$category->id}}"><a href="{{$category->url?:route('tour.index')}}" class="destination-feature-box"><div class="icon"><img src="{{Storage::url($category->icon_image)}}" alt="{{$category->name}}"></div><div class="content"><h6>{{$category->name}}</h6><span><b>{{$category->tour_count}}</b> Tours - From <b>${{number_format((float)$category->starting_price,0)}}</b></span></div></a></div>@endforeach</div>@endif
@if($promo)<div class="cta-wrapper-4 section-padding bg-cover" style="background-image:url('{{Storage::url($promo->background_image)}}')"><div class="section-title text-center mb-0"><span>{{$promo->subtitle}}</span><h2 class="text-white">{{$promo->title}}</h2></div><a href="{{$promo->button_url}}" class="theme-btn"><span>{{$promo->button_text}}</span> <i class="far fa-long-arrow-right"></i></a></div>@endif</div></section>@endif

@if($testimonials->isNotEmpty())<section class="testimonial-section-4 section-padding"><div class="container"><div class="section-title-area"><div class="section-title"><span>Our Testimonials</span><h2>Real Feedback from Happy Travelers</h2></div></div><div class="swiper testimonial-slider-4"><div class="swiper-wrapper">@foreach($testimonials as $testimonial)<div class="swiper-slide" wire:key="testimonial-{{$testimonial->id}}"><div class="testimonial-box-items-4">@if($testimonial->image)<div class="testi-img"><img src="{{Storage::url($testimonial->image)}}" alt="{{$testimonial->name}}"></div>@endif<div class="star">@for($i=1;$i<=5;$i++)<i class="{{$i<=$testimonial->rating?'fas':'far'}} fa-star"></i>@endfor</div><h3>“{{$testimonial->quote}}”</h3><div class="client-info"><h4>{{$testimonial->name}}</h4>@if($testimonial->location)<span>{{$testimonial->location}}</span>@endif</div></div></div>@endforeach</div></div></div></section>@endif

@if($articles->isNotEmpty())<section class="news-section section-padding section-bg-2"><div class="container"><div class="section-title text-center"><span>Latest Blog & News</span><h2>Latest Travel Insights and Destination Guides</h2></div><div class="row">@foreach($articles as $article)<div class="col-xl-4 col-lg-6 col-md-6" wire:key="article-{{$article->id}}"><div class="news-box-items-4"><div class="news-img"><img src="{{Storage::url($article->image)}}" alt="{{$article->title}}"><ul class="post-date"><li>{{$article->published_at->format('d')}}</li><li>{{$article->published_at->format('M')}}</li></ul></div><div class="news-content"><ul><li><b>By</b> {{$article->author}}</li></ul><h3><a href="{{route('news.show',$article)}}">{{$article->title}}</a></h3><p>{{$article->excerpt}}</p><a href="{{route('news.show',$article)}}" class="link-btn">Continue Reading <i class="far fa-long-arrow-right"></i></a></div></div></div>@endforeach</div></div></section>@endif

@if($appPromotion)<section class="cta-app-section fix section-padding bg-cover" @if($appPromotion->background_image) style="background-image:url('{{Storage::url($appPromotion->background_image)}}')" @endif><div class="container"><div class="row align-items-center g-4"><div class="col-lg-7"><div class="section-title"><span class="text-white">{{$appPromotion->subtitle}}</span><h2 class="text-white">{{$appPromotion->title}}</h2></div>@if($appPromotion->description)<p class="text-white">{{$appPromotion->description}}</p>@endif<div class="d-flex gap-3 mt-4">@if($appPromotion->play_store_url)<a href="{{$appPromotion->play_store_url}}" class="theme-btn"><span>Google Play</span></a>@endif @if($appPromotion->app_store_url)<a href="{{$appPromotion->app_store_url}}" class="theme-btn"><span>App Store</span></a>@endif</div></div>@if($appPromotion->app_image)<div class="col-lg-5"><img class="img-fluid" src="{{Storage::url($appPromotion->app_image)}}" alt="{{$appPromotion->title}}"></div>@endif</div></div></section>@endif
</div>
