@extends('backend.layouts.app')
@section('content')
<div class="card"><div class="card-header"><h4>Edit {{ $page->title }}</h4></div><div class="card-body">@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif<form method="POST" enctype="multipart/form-data" action="{{route('admin.content-pages.update',$page)}}" class="row g-3">@csrf @method('PUT')
<div class="col-md-6"><label class="form-label">Page title</label><input class="form-control" name="title" value="{{old('title',$page->title)}}" required></div><div class="col-md-6"><label class="form-label">Breadcrumb title</label><input class="form-control" name="breadcrumb_title" value="{{old('breadcrumb_title',$page->breadcrumb_title)}}"></div>
<div class="col-md-6"><label class="form-label">Meta title</label><input class="form-control" name="meta_title" value="{{old('meta_title',$page->meta_title)}}"></div><div class="col-md-6"><label class="form-label">Breadcrumb background</label><input type="file" class="form-control" name="breadcrumb_image" accept="image/*"></div>
<div class="col-12"><label class="form-label">Meta description</label><textarea class="form-control" name="meta_description" rows="2">{{old('meta_description',$page->meta_description)}}</textarea></div><div class="col-12"><label class="form-label">Main content</label><textarea class="form-control" name="content" rows="8">{{old('content',$page->content)}}</textarea></div>
<div class="col-12"><label class="form-label">Section configuration (JSON)</label><textarea class="form-control font-monospace @error('sections') is-invalid @enderror" name="sections" rows="14">{{old('sections',json_encode($page->sections?:new stdClass,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))}}</textarea><small class="text-muted">About controls promises, counters and destination/team/app/news visibility. FAQ stores question/answer items.</small>@error('sections')<div class="invalid-feedback">{{$message}}</div>@enderror</div>
<div class="col-12"><label class="form-check"><input type="checkbox" class="form-check-input" name="is_active" value="1" @checked(old('is_active',$page->is_active))> Published</label></div><div class="col-12"><button class="btn btn-primary">Save page</button> <a class="btn btn-light" href="{{route('admin.content-pages.index')}}">Back</a></div></form></div></div>
@endsection
