@php($logo = $settings->logo ? asset('storage/'.$settings->logo) : asset('assets/frontend/img/logo/aventro.png'))
<footer class="footer-section fix section-bg bg-cover" style="background-image:url('{{ asset('assets/frontend/img/footer/bg-image.jpg') }}')"><div class="container">
<div class="footer-newsletter-items"><h2>{{ $settings->newsletter_title ?: 'Get Our Latest Travel Updates' }}</h2><form method="POST" action="{{ route('newsletter.subscribe') }}" class="footer-input">@csrf<input type="text" name="website" tabindex="-1" style="position:absolute;left:-9999px" aria-hidden="true"><input type="email" name="newsletter_email" placeholder="Enter your email" required><button class="newsletter-btn" type="submit">Subscribe <i class="far fa-search"></i></button></form>@if(session('newsletter_success'))<div class="text-white mt-2">{{ session('newsletter_success') }}</div>@endif</div>
<div class="footer-wrapper"><div class="row"><div class="col-xl-5 col-lg-7 col-md-12"><div class="footer-widget-items"><div class="widget-title"><a href="{{ route('home') }}" class="footer-logo"><img src="{{ $logo }}" alt="{{ $settings->site_name }}"></a></div><div class="footer-content"><div class="contact-info-items">
@if($settings->phone)<div class="contact-items"><div class="icon"><img src="{{ asset('assets/frontend/img/call.png') }}" alt=""></div><div class="content"><span>Call Us</span><h6><a href="tel:{{ preg_replace('/[^+0-9]/','',$settings->phone) }}">{{ $settings->phone }}</a></h6></div></div>@endif
@if($settings->email)<div class="contact-items"><div class="icon"><img src="{{ asset('assets/frontend/img/mail.png') }}" alt=""></div><div class="content"><span>Mail Us</span><h6><a href="mailto:{{ $settings->email }}">{{ $settings->email }}</a></h6></div></div>@endif</div>
@if($settings->tagline)<h6 class="app-text">{{ $settings->tagline }}</h6>@endif<div class="apps-items">@if($settings->app_store_url)<a href="{{ $settings->app_store_url }}"><img src="{{ asset('assets/frontend/img/apply-store.png') }}" alt="App Store"></a>@endif @if($settings->play_store_url)<a href="{{ $settings->play_store_url }}"><img src="{{ asset('assets/frontend/img/play-store.jpg') }}" alt="Google Play"></a>@endif</div><div class="social-icon">@foreach(['facebook'=>'facebook-f','instagram'=>'instagram','twitter'=>'twitter','linkedin'=>'linkedin-in'] as $network=>$icon) @if($settings->{$network.'_url'})<a href="{{ $settings->{$network.'_url'} }}" target="_blank" rel="noopener"><i class="fab fa-{{ $icon }}"></i></a>@endif @endforeach</div></div></div></div>
@foreach($linkGroups as $group => $links)<div class="col-xl-2 col-lg-4 col-md-4 col-sm-6"><div class="footer-widget-items"><div class="widget-title"><h3>{{ $group }}</h3></div><ul class="list-items">@foreach($links as $link)<li><a href="{{ $link->url }}">{{ $link->label }}</a></li>@endforeach</ul></div></div>@endforeach
@if($gallery->isNotEmpty())<div class="col-xl-3 col-lg-4 col-md-4"><div class="footer-widget-items"><div class="widget-title"><h3>Gallery</h3></div><div class="footer-gallery"><div class="gallery-wrap"><div class="gallery-item">@foreach($gallery as $item)<div class="thumb"><a href="{{ $item->url ?: asset('storage/'.$item->image) }}" class="img-popup"><img src="{{ asset('storage/'.$item->image) }}" alt="{{ $item->alt_text ?: 'Gallery image' }}"><div class="icon"><i class="far fa-plus"></i></div></a></div>@endforeach</div></div></div></div></div>@endif
</div></div></div><div class="footer-bottom-1"><div class="container"><div class="footer-bottom-wrapper"><p>{{ $settings->copyright_text ?: '© '.date('Y').' '.$settings->site_name.'. All rights reserved.' }}</p></div></div></div></footer>
