@php($logo = $settings->logo ? asset('storage/'.$settings->logo) : asset('assets/frontend/img/logo/aventro.png'))
<header class="header-section header-inner">
<div class="header-top-section"><div class="container-fluid"><div class="header-top-wrapper"><ul class="top-left">
@if($settings->email)<li><i class="far fa-envelope"></i><a href="mailto:{{ $settings->email }}">{{ $settings->email }}</a></li>@endif
@if($settings->address)<li><i class="far fa-map-marker-alt"></i>{{ $settings->address }}</li>@endif
</ul><div class="d-flex align-items-center gap-3"><form method="POST" action="{{ route('preferences.update') }}" class="d-flex gap-2">@csrf
@if($currencies->isNotEmpty())<select name="currency" onchange="this.form.submit()" aria-label="Currency">@foreach($currencies as $currency)<option value="{{ $currency->code }}" @selected(session('currency','USD') === $currency->code)>{{ $currency->code }}</option>@endforeach</select>@endif
@if($languages->isNotEmpty())<select name="language" onchange="this.form.submit()" aria-label="Language">@foreach($languages as $language)<option value="{{ $language->code }}" @selected(session('language',app()->getLocale()) === $language->code)>{{ $language->name }}</option>@endforeach</select>@endif
</form><div class="social-icon">@foreach(['facebook'=>'facebook-f','instagram'=>'instagram','twitter'=>'twitter','linkedin'=>'linkedin-in'] as $network=>$icon) @if($settings->{$network.'_url'})<a href="{{ $settings->{$network.'_url'} }}" target="_blank" rel="noopener"><i class="fab fa-{{ $icon }}"></i></a>@endif @endforeach</div></div></div></div></div>
<div id="header-sticky" class="header-1 header-4"><div class="container-fluid"><div class="mega-menu-wrapper"><div class="header-main"><div class="header-left"><div class="logo"><a href="{{ route('home') }}" class="header-logo"><img src="{{ $logo }}" alt="{{ $settings->site_name }}"></a></div></div><div class="header-right d-flex justify-content-end align-items-center"><div class="mean__menu-wrapper"><div class="main-menu"><livewire:frontend.theme.menu /></div></div>
@if($settings->phone)<div class="contact-items"><div class="icon"><img src="{{ asset('assets/frontend/img/call.png') }}" alt=""></div><div class="content"><span>Call Us</span><h6><a href="tel:{{ preg_replace('/[^+0-9]/', '', $settings->phone) }}">{{ $settings->phone }}</a></h6></div></div>@endif
<div class="header-search"><button class="d-flex align-items-center search-toggle" aria-label="Search"><i class="far fa-search"></i></button></div>@if($settings->header_button_text)<a href="{{ $settings->header_button_url ?: route('tour.index') }}" class="theme-btn"><span>{{ $settings->header_button_text }}</span> <i class="far fa-long-arrow-right"></i></a>@endif<div class="header__hamburger d-xl-none my-auto"><div class="sidebar__toggle"><div class="header-bar"><span></span><span></span><span></span></div></div></div></div></div></div></div></div>
</header>
