@extends('frontend.layouts.app')
@section('title','Travel News | Aventaro')
@section('meta_description','Travel inspiration, destination guides, and the latest Aventaro news.')
@section('content')
<div class="breadcrumb-wrapper section-padding bg-cover" style="background-image:url('{{asset('assets/frontend/img/breadcrumb-bg.jpg')}}')"><div class="container-fluid"><div class="page-heading"><ul class="breadcrumb-items"><li><a href="{{route('home')}}">Home</a></li><li><i class="far fa-slash"></i></li><li>Blog & News</li></ul><h1>Blog & News</h1></div></div></div>
<section class="blog-wrapper news-wrapper section-padding"><div class="container"><div class="news-area"><div class="row"><div class="col-12 col-xl-8 col-lg-7"><div class="blog-posts">
@forelse($posts as $post)<article class="single-blog-post"><a href="{{route('news.show',$post)}}"><div class="post-featured-thumb bg-cover" style="background-image:url('{{Storage::url($post->image)}}')"></div></a><div class="post-content"><div class="post-meta"><span><i class="fal fa-user"></i>{{$post->author}}</span><span><i class="fal fa-calendar-alt"></i>{{$post->published_at->format('F j, Y')}}</span>@if($post->category)<span><i class="fal fa-folder"></i>{{$post->category->name}}</span>@endif</div><h2><a href="{{route('news.show',$post)}}">{{$post->title}}</a></h2><p>{{$post->excerpt}}</p><a href="{{route('news.show',$post)}}" class="theme-btn mt-4"><span>Read More</span> <i class="far fa-long-arrow-right"></i></a></div></article>@empty<div class="text-center py-5"><h3>No published articles found</h3><p>Try changing your search or filters.</p></div>@endforelse
</div><div class="mt-5">{{$posts->links()}}</div></div><aside class="col-12 col-xl-4 col-lg-5"><div class="main-sidebar sticky-style">
<div class="single-sidebar-widget"><div class="wid-title"><h3>Search</h3></div><div class="search_widget"><form action="{{route('news.index')}}"><input name="search" value="{{request('search')}}" placeholder="Keywords here..."><button><i class="fal fa-search"></i></button></form></div></div>
@if($popularPosts->isNotEmpty())<div class="single-sidebar-widget"><div class="wid-title"><h3>Popular Articles</h3></div><div class="popular-posts">@foreach($popularPosts as $popular)<div class="single-post-item"><div class="thumb bg-cover" style="background-image:url('{{Storage::url($popular->image)}}')"></div><div class="post-content"><h5><a href="{{route('news.show',$popular)}}">{{$popular->title}}</a></h5><div class="post-date"><i class="far fa-eye"></i>{{$popular->view_count}} views</div></div></div>@endforeach</div></div>@endif
@if($latestPosts->isNotEmpty())<div class="single-sidebar-widget"><div class="wid-title"><h3>Latest Articles</h3></div><ul class="list-unstyled">@foreach($latestPosts as $latest)<li class="mb-3"><a href="{{route('news.show',$latest)}}"><strong>{{$latest->title}}</strong></a><br><small>{{$latest->published_at->format('M j, Y')}}</small></li>@endforeach</ul></div>@endif
@if($categories->isNotEmpty())<div class="single-sidebar-widget"><div class="wid-title"><h3>Categories</h3></div><div class="widget_categories"><ul>@foreach($categories as $category)<li><a href="{{route('news.index',['category'=>$category->slug])}}">{{$category->name}} <span>{{$category->posts_count}}</span></a></li>@endforeach</ul></div></div>@endif
@if($tags->isNotEmpty())<div class="single-sidebar-widget"><div class="wid-title"><h3>Tags</h3></div><div class="tagcloud">@foreach($tags as $tag)<a href="{{route('news.index',['tag'=>$tag->slug])}}">{{$tag->name}}</a>@endforeach</div></div>@endif
</div></aside></div></div></div></section>
@endsection
