@extends('frontend.layouts.app')
@section('title',$post->title.' | Aventaro')
@section('meta_description',Str::limit(strip_tags($post->excerpt),155))
@section('canonical',route('news.show',$post))
@section('og_type','article')
@section('social_image',Storage::url($post->image))
@push('structured-data')<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'Article','headline'=>$post->title,'description'=>$post->excerpt,'image'=>Storage::url($post->image),'datePublished'=>$post->published_at?->toAtomString(),'dateModified'=>$post->updated_at->toAtomString(),'author'=>['@type'=>'Person','name'=>$post->author],'mainEntityOfPage'=>route('news.show',$post)],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>@endpush
@section('content')
<div class="breadcrumb-wrapper section-padding bg-cover" style="background-image:url('{{asset('assets/frontend/img/breadcrumb-bg.jpg')}}')"><div class="container-fluid"><div class="page-heading"><ul class="breadcrumb-items"><li><a href="{{route('home')}}">Home</a></li><li><i class="far fa-slash"></i></li><li><a href="{{route('news.index')}}">News</a></li><li><i class="far fa-slash"></i></li><li>{{$post->title}}</li></ul><h1>{{$post->title}}</h1></div></div></div>
<section class="blog-wrapper news-wrapper section-padding"><div class="container"><div class="row justify-content-center"><article class="col-lg-9"><img class="img-fluid w-100 rounded mb-4" src="{{Storage::url($post->image)}}" alt="{{$post->title}}"><div class="post-meta d-flex flex-wrap gap-4 mb-3"><span><i class="fal fa-user"></i> {{$post->author}}</span><span><i class="fal fa-calendar-alt"></i> {{$post->published_at->format('F j, Y')}}</span><span><i class="fal fa-eye"></i> {{$post->view_count}} views</span>@if($post->category)<a href="{{route('news.index',['category'=>$post->category->slug])}}">{{$post->category->name}}</a>@endif</div><h2>{{$post->title}}</h2><p class="lead">{{$post->excerpt}}</p><div class="article-content">{!! nl2br(e($post->content ?: $post->excerpt)) !!}</div>@if($post->tags->isNotEmpty())<div class="tagcloud mt-5">@foreach($post->tags as $tag)<a href="{{route('news.index',['tag'=>$tag->slug])}}">{{$tag->name}}</a>@endforeach</div>@endif</article></div>
@if($related->isNotEmpty())<div class="mt-5 pt-4"><h2>Related Articles</h2><div class="row g-4 mt-2">@foreach($related as $item)<div class="col-lg-4"><div class="news-box-items-4"><div class="news-img"><img src="{{Storage::url($item->image)}}" alt="{{$item->title}}"></div><div class="news-content"><h3><a href="{{route('news.show',$item)}}">{{$item->title}}</a></h3><p>{{$item->excerpt}}</p></div></div></div>@endforeach</div></div>@endif
</div></section>
@endsection
